apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
spec:
  selector:
    matchLabels:
      app: alpine
  replicas: 1
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
        - name: alpine
          image: alpine
          volumeMounts:
            - name: env-vol
              mountPath: /.env
          command: ["ash"]
      volumes:
        - name: env-vol
          configMap:
            name: env
      imagePullPolicy: Always
