apiVersion: batch/v1
kind: Job
metadata:
  name: env-job
spec:
  template:
    spec:
      containers:
        - name: env-job
          image: alpine
          volumeMounts:
            - name: env-vol
              mountPath: /.env
          command: ["ls", ".env"]
          restartPolicy: OnFailure
      volumes:
        - name: env-vol
          configMap:
            name: env
  backoffLimit: 5
